"""프로토타입 카탈로그 및 앱 설정 테이블 추가

Revision ID: 017
Revises: 016
Create Date: 2026-04-21 12:00:00.000000
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = "017"
down_revision: str | tuple[str, ...] | None = "016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    now = datetime.now(UTC).replace(tzinfo=None)

    # ── prototype_tags ─────────────────────────────────────────────────────────
    op.create_table(
        "prototype_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("label_ko", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prototype_tags_slug"), "prototype_tags", ["slug"], unique=True
    )

    # ── prototype_catalog_entries ──────────────────────────────────────────────
    op.create_table(
        "prototype_catalog_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("primary_tag", sa.String(length=100), nullable=True),
        sa.Column("design_pattern", sa.String(length=100), nullable=True),
        sa.Column("architecture_pattern", sa.String(length=200), nullable=True),
        sa.Column("tech_stack_tags", sa.JSON(), nullable=False),
        sa.Column("pros", sa.JSON(), nullable=False),
        sa.Column("cons", sa.JSON(), nullable=False),
        sa.Column("ui_structure", sa.JSON(), nullable=False),
        sa.Column("menu_structure", sa.JSON(), nullable=False),
        sa.Column("color_palette", sa.JSON(), nullable=False),
        sa.Column("design_philosophy", sa.Text(), nullable=True),
        sa.Column("implementation_constraints", sa.JSON(), nullable=False),
        sa.Column("recommended_agents", sa.JSON(), nullable=False),
        sa.Column("optional_agents", sa.JSON(), nullable=False),
        sa.Column("excluded_agents", sa.JSON(), nullable=False),
        sa.Column("recommended_skills", sa.JSON(), nullable=False),
        sa.Column("agent_strategy", sa.Text(), nullable=True),
        sa.Column("task_distribution_guide", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prototype_catalog_entries_slug"),
        "prototype_catalog_entries",
        ["slug"],
        unique=True,
    )
    op.create_index(
        op.f("ix_prototype_catalog_entries_primary_tag"),
        "prototype_catalog_entries",
        ["primary_tag"],
        unique=False,
    )

    # ── app_settings ───────────────────────────────────────────────────────────
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(100), primary_key=True),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_by",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    # ── seed: prototype_tags ───────────────────────────────────────────────────
    tag_table = sa.table(
        "prototype_tags",
        sa.column("id", sa.Uuid()),
        sa.column("slug", sa.String()),
        sa.column("label", sa.String()),
        sa.column("label_ko", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("color", sa.String()),
        sa.column("is_active", sa.Boolean()),
        sa.column("sort_order", sa.Integer()),
    )
    op.bulk_insert(
        tag_table,
        [
            {
                "id": uuid.uuid4(), "slug": "saas", "label": "SaaS", "label_ko": "SaaS 플랫폼",
                "description": "구독형 서비스, 멀티테넌트 지원",
                "color": "#3B82F6", "is_active": True, "sort_order": 0,
            },
            {
                "id": uuid.uuid4(), "slug": "rest-api", "label": "REST API", "label_ko": "REST API 서비스",
                "description": "API 우선 설계, OpenAPI 스펙",
                "color": "#8B5CF6", "is_active": True, "sort_order": 1,
            },
            {
                "id": uuid.uuid4(), "slug": "fullstack", "label": "Fullstack", "label_ko": "풀스택 웹",
                "description": "프론트/백 통합 웹 애플리케이션",
                "color": "#10B981", "is_active": True, "sort_order": 2,
            },
            {
                "id": uuid.uuid4(), "slug": "internal-tool", "label": "Internal Tool", "label_ko": "내부 도구",
                "description": "사내 운영/관리 도구",
                "color": "#F59E0B", "is_active": True, "sort_order": 3,
            },
            {
                "id": uuid.uuid4(), "slug": "mvp", "label": "MVP", "label_ko": "빠른 MVP",
                "description": "최소 기능으로 빠른 출시",
                "color": "#EF4444", "is_active": True, "sort_order": 4,
            },
            {
                "id": uuid.uuid4(), "slug": "custom", "label": "Custom", "label_ko": "커스텀",
                "description": "요구사항 기반 자유 설계",
                "color": "#6B7280", "is_active": True, "sort_order": 5,
            },
        ],
    )

    # ── seed: prototype_catalog_entries (15개) ────────────────────────────────
    entry_table = sa.table(
        "prototype_catalog_entries",
        sa.column("id", sa.Uuid()),
        sa.column("slug", sa.String()),
        sa.column("title", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("tags", sa.JSON()),
        sa.column("primary_tag", sa.String()),
        sa.column("design_pattern", sa.String()),
        sa.column("architecture_pattern", sa.String()),
        sa.column("tech_stack_tags", sa.JSON()),
        sa.column("pros", sa.JSON()),
        sa.column("cons", sa.JSON()),
        sa.column("ui_structure", sa.JSON()),
        sa.column("menu_structure", sa.JSON()),
        sa.column("color_palette", sa.JSON()),
        sa.column("design_philosophy", sa.Text()),
        sa.column("implementation_constraints", sa.JSON()),
        sa.column("recommended_agents", sa.JSON()),
        sa.column("optional_agents", sa.JSON()),
        sa.column("excluded_agents", sa.JSON()),
        sa.column("recommended_skills", sa.JSON()),
        sa.column("agent_strategy", sa.Text()),
        sa.column("task_distribution_guide", sa.Text()),
        sa.column("is_active", sa.Boolean()),
        sa.column("priority", sa.Integer()),
        sa.column("created_at", sa.DateTime()),
        sa.column("updated_at", sa.DateTime()),
    )
    op.bulk_insert(entry_table, [
        # SaaS
        {
            "id": uuid.uuid4(), "slug": "saas-nextjs-fastapi-standard",
            "title": "SaaS 표준형 (Next.js + FastAPI + PostgreSQL)",
            "description": "SaaS 서비스의 검증된 풀스택 조합. SSR/SSG와 비동기 API를 결합합니다.",
            "tags": ["saas", "fullstack", "multi-tenant"], "primary_tag": "saas",
            "design_pattern": "saas-fullstack", "architecture_pattern": "모놀리식 3-tier",
            "tech_stack_tags": ["Next.js", "FastAPI", "PostgreSQL", "Docker"],
            "pros": ["검증된 조합, 레퍼런스 풍부", "SSR로 SEO·초기 로딩 우수", "비동기 API로 높은 처리량"],
            "cons": ["프론트/백 분리 배포로 운영 복잡도↑", "Python 서버 cold start 존재"],
            "ui_structure": {"frontend": "next.js", "backend": "fastapi", "database": "postgresql", "auth": "jwt", "deployment": "docker"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "SaaS 플랫폼 구축: 멀티테넌트 지원, 구독 과금, 인증 플로우를 핵심 축으로 설계",
            "implementation_constraints": ["멀티테넌트 데이터 격리 필수", "구독/결제 플로우 초기부터 설계", "인증 미들웨어 전 레이어 적용"],
            "recommended_agents": ["backend", "frontend", "devops"],
            "optional_agents": ["uiux"], "excluded_agents": [],
            "recommended_skills": ["tdd", "linear"],
            "agent_strategy": "백엔드 API(인증·구독) → 프론트엔드(대시보드·랜딩) → DevOps(CI/CD) 순으로 구현",
            "task_distribution_guide": "backend agent: 인증/결제/API. frontend agent: 랜딩·대시보드 UI. devops agent: 배포 자동화.",
            "is_active": True, "priority": 10, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "saas-vue-django-lightweight",
            "title": "SaaS 경량형 (Vue.js + Django + PostgreSQL)",
            "description": "Django의 강력한 ORM과 Vue.js의 반응형 UI를 조합한 대안 스택.",
            "tags": ["saas", "fullstack"], "primary_tag": "saas",
            "design_pattern": "saas-django", "architecture_pattern": "MVC 모놀리식",
            "tech_stack_tags": ["Vue.js", "Django", "PostgreSQL", "Nginx"],
            "pros": ["Django 어드민으로 백오피스 즉시 확보", "배터리-인클루디드 프레임워크", "Python 생태계 재사용"],
            "cons": ["GIL로 동시성 제약", "Django REST Framework 설정 verbose"],
            "ui_structure": {"frontend": "vue.js", "backend": "django", "database": "postgresql", "auth": "session", "deployment": "nginx"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "Django 내장 기능 최대 활용, 빠른 백오피스·어드민 구축 우선",
            "implementation_constraints": ["Django ORM 패턴 준수", "Class-based View 활용", "DRF Serializer 일관성 유지"],
            "recommended_agents": ["backend", "frontend"], "optional_agents": ["devops"], "excluded_agents": [],
            "recommended_skills": ["tdd"],
            "agent_strategy": "Django 백엔드(모델·API·어드민) → Vue.js 프론트엔드 순 구현",
            "task_distribution_guide": "backend agent: Django 모델·API·어드민. frontend agent: Vue 컴포넌트.",
            "is_active": True, "priority": 5, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "saas-react-lambda-serverless",
            "title": "SaaS 서버리스형 (React + AWS Lambda + DynamoDB)",
            "description": "서버 관리 없이 트래픽에 따라 자동 스케일링되는 서버리스 아키텍처.",
            "tags": ["saas", "serverless", "aws"], "primary_tag": "saas",
            "design_pattern": "saas-serverless", "architecture_pattern": "서버리스 이벤트 기반",
            "tech_stack_tags": ["React", "AWS Lambda", "DynamoDB", "API Gateway"],
            "pros": ["트래픽 0일 때 비용 없음", "인프라 관리 최소화", "자동 스케일링"],
            "cons": ["Cold start 지연 (첫 요청)", "복잡한 트랜잭션 처리 어려움", "벤더 락인(AWS)"],
            "ui_structure": {"frontend": "react", "backend": "aws-lambda", "database": "dynamodb", "auth": "cognito", "deployment": "serverless"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "서버리스 우선: 이벤트 기반 설계, 상태를 DynamoDB에 위임, 함수 단위 배포",
            "implementation_constraints": ["Lambda 함수는 stateless 유지", "Cold start 최소화를 위한 번들 크기 관리", "DynamoDB 액세스 패턴 설계 우선"],
            "recommended_agents": ["backend", "devops"], "optional_agents": ["frontend"], "excluded_agents": [],
            "recommended_skills": ["tdd"],
            "agent_strategy": "Lambda 함수 설계·구현 → API Gateway 설정 → React 프론트 연동",
            "task_distribution_guide": "backend agent: Lambda·DynamoDB. devops agent: SAM/CDK 배포.",
            "is_active": True, "priority": 3, "created_at": now, "updated_at": now,
        },
        # REST API
        {
            "id": uuid.uuid4(), "slug": "rest-api-fastapi-standard",
            "title": "REST API 표준형 (FastAPI + PostgreSQL)",
            "description": "자동 OpenAPI 문서와 비동기 처리가 강점인 Python REST API.",
            "tags": ["rest-api", "python"], "primary_tag": "rest-api",
            "design_pattern": "api-first", "architecture_pattern": "API-first 모놀리식",
            "tech_stack_tags": ["FastAPI", "PostgreSQL", "Redis", "Docker"],
            "pros": ["자동 OpenAPI/Swagger 문서", "비동기로 높은 처리량", "Pydantic 검증 내장"],
            "cons": ["Python 생태계 의존", "대규모 시 수평 확장 설계 필요"],
            "ui_structure": {"framework": "fastapi", "database": "postgresql", "auth": "jwt", "docs": "openapi", "deployment": "docker"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "API-first: OpenAPI 스펙 우선 설계, 엔드포인트 계약 명확화",
            "implementation_constraints": ["OpenAPI 스펙 우선 작성 후 구현", "Pydantic 스키마로 입출력 엄격 검증", "비동기 DB 쿼리 일관 사용"],
            "recommended_agents": ["backend"], "optional_agents": ["devops"], "excluded_agents": ["frontend", "uiux"],
            "recommended_skills": ["tdd"],
            "agent_strategy": "OpenAPI 스펙 → FastAPI 라우터 → 서비스 레이어 → DB 모델 순 구현",
            "task_distribution_guide": "backend agent 단독 구현. OpenAPI 문서 자동 생성 활용.",
            "is_active": True, "priority": 10, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "rest-api-express-mongodb-nodejs",
            "title": "REST API Node.js형 (Express + MongoDB)",
            "description": "유연한 스키마와 JS 풀스택이 강점인 Node.js API 서버.",
            "tags": ["rest-api", "nodejs", "javascript"], "primary_tag": "rest-api",
            "design_pattern": "api-nodejs", "architecture_pattern": "API-first 모놀리식",
            "tech_stack_tags": ["Express", "MongoDB", "Node.js", "Docker"],
            "pros": ["JS 단일 언어로 프론트/백 통일", "유연한 스키마 설계", "npm 생태계 방대"],
            "cons": ["타입 안전성 약함 (TS 필수)", "MongoDB 트랜잭션 제약"],
            "ui_structure": {"framework": "express", "database": "mongodb", "auth": "jwt", "docs": "swagger", "deployment": "docker"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "JS 단일 언어 풀스택: 프론트/백 타입 공유, MongoDB 유연한 스키마 활용",
            "implementation_constraints": ["TypeScript 필수 사용", "Mongoose 스키마로 데이터 구조 정의", "Jest로 단위 테스트"],
            "recommended_agents": ["backend"], "optional_agents": ["devops"], "excluded_agents": ["frontend", "uiux"],
            "recommended_skills": ["tdd"],
            "agent_strategy": "Express 라우터 → Mongoose 모델 → 미들웨어 → 테스트 순 구현",
            "task_distribution_guide": "backend agent: Express·Mongoose·인증 미들웨어.",
            "is_active": True, "priority": 5, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "rest-api-go-gin-high-performance",
            "title": "REST API 고성능형 (Go Gin + PostgreSQL)",
            "description": "초저지연·고처리량이 필요한 API에 최적화된 Go 기반 구성.",
            "tags": ["rest-api", "go", "high-performance"], "primary_tag": "rest-api",
            "design_pattern": "api-go", "architecture_pattern": "마이크로서비스 지향",
            "tech_stack_tags": ["Go", "Gin", "PostgreSQL", "gRPC", "Kubernetes"],
            "pros": ["초고속 처리량 (동시 수만 req)", "메모리 효율 최고", "컴파일 타입 안전성"],
            "cons": ["Go 개발자 채용 풀 협소", "초기 개발 속도 느림", "제네릭 생태계 아직 성숙 중"],
            "ui_structure": {"framework": "gin", "database": "postgresql", "auth": "jwt", "deployment": "kubernetes"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "성능 우선: 최소 추상화, 직접 SQL, goroutine 병렬 처리",
            "implementation_constraints": ["추상화 레이어 최소화", "직접 SQL 쿼리 사용 (ORM 지양)", "에러 핸들링 명시적 처리"],
            "recommended_agents": ["backend", "devops"], "optional_agents": [], "excluded_agents": ["frontend", "uiux"],
            "recommended_skills": ["tdd"],
            "agent_strategy": "Go 모듈 구조 → Gin 라우터 → 핸들러 → Kubernetes 배포 설정",
            "task_distribution_guide": "backend agent: Go 핸들러·미들웨어. devops agent: K8s 매니페스트.",
            "is_active": True, "priority": 3, "created_at": now, "updated_at": now,
        },
        # Fullstack
        {
            "id": uuid.uuid4(), "slug": "fullstack-nextjs-fastapi-separated",
            "title": "풀스택 표준형 (Next.js + FastAPI + PostgreSQL)",
            "description": "프론트/백 분리 배포의 검증된 풀스택 구성.",
            "tags": ["fullstack", "saas"], "primary_tag": "fullstack",
            "design_pattern": "fullstack-separated", "architecture_pattern": "풀스택 분리 배포",
            "tech_stack_tags": ["Next.js", "FastAPI", "PostgreSQL", "Docker Compose"],
            "pros": ["프론트/백 독립 배포·스케일링", "각 레이어 최적 기술 선택", "타입 공유 가능"],
            "cons": ["CORS·API 연동 설정 필요", "두 런타임 관리"],
            "ui_structure": {"frontend": "next.js", "backend": "fastapi", "database": "postgresql", "auth": "jwt", "deployment": "docker-compose"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "프론트/백 명확 분리: 각 레이어 독립 배포·스케일링 가능",
            "implementation_constraints": ["API 계약(OpenAPI) 우선 정의", "CORS 설정 환경별 분리", "프론트·백 독립 CI/CD"],
            "recommended_agents": ["backend", "frontend", "devops"], "optional_agents": ["uiux"], "excluded_agents": [],
            "recommended_skills": ["tdd", "linear"],
            "agent_strategy": "백엔드 API 설계 → 프론트엔드 구현 → DevOps 파이프라인",
            "task_distribution_guide": "backend agent: FastAPI. frontend agent: Next.js. devops agent: Docker Compose·CI.",
            "is_active": True, "priority": 10, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "fullstack-remix-prisma-integrated",
            "title": "풀스택 통합형 (Remix + Prisma + PostgreSQL)",
            "description": "서버 컴포넌트와 로더로 프론트/백을 통합하는 현대적 풀스택.",
            "tags": ["fullstack", "nodejs"], "primary_tag": "fullstack",
            "design_pattern": "fullstack-remix", "architecture_pattern": "풀스택 통합 SSR",
            "tech_stack_tags": ["Remix", "Prisma", "PostgreSQL", "Fly.io"],
            "pros": ["서버/클라이언트 코드 통합", "Form 기반 데이터 뮤테이션 내장", "빠른 페이지 전환"],
            "cons": ["Remix 학습 곡선", "생태계가 Next.js 대비 작음"],
            "ui_structure": {"frontend": "remix", "backend": "remix-loaders", "database": "postgresql", "orm": "prisma", "auth": "remix-auth", "deployment": "fly.io"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "풀스택 통합: 서버 로더와 클라이언트 컴포넌트 경계 최소화",
            "implementation_constraints": ["Loader/Action 패턴 일관 사용", "Prisma 마이그레이션 관리", "Progressive Enhancement 원칙"],
            "recommended_agents": ["backend", "frontend"], "optional_agents": ["devops"], "excluded_agents": [],
            "recommended_skills": ["tdd"],
            "agent_strategy": "Remix 라우트 구조 → Loader·Action → Prisma 모델 → 배포",
            "task_distribution_guide": "단일 fullstack agent로 Remix 통합 구현 권장.",
            "is_active": True, "priority": 5, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "fullstack-nextjs-supabase-baas",
            "title": "풀스택 BaaS형 (Next.js + Supabase)",
            "description": "Supabase로 DB·Auth·Storage를 일괄 관리하는 서버리스 풀스택.",
            "tags": ["fullstack", "serverless", "baas"], "primary_tag": "fullstack",
            "design_pattern": "fullstack-baas", "architecture_pattern": "BaaS 기반 서버리스",
            "tech_stack_tags": ["Next.js", "Supabase", "PostgreSQL", "Vercel"],
            "pros": ["백엔드 코드 거의 불필요", "실시간 구독·Auth 즉시 사용", "Vercel+Supabase 무료 티어"],
            "cons": ["Supabase 벤더 의존", "복잡한 비즈니스 로직 구현 제약", "Row-level security 설계 필요"],
            "ui_structure": {"frontend": "next.js", "backend": "supabase", "database": "supabase-postgres", "auth": "supabase-auth", "deployment": "vercel"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "BaaS 위임: Supabase에 DB·Auth·Storage를 맡기고 비즈니스 로직에 집중",
            "implementation_constraints": ["Row Level Security(RLS) 필수 설계", "Supabase Edge Functions로 서버 로직 처리", "실시간 구독은 Supabase Realtime 활용"],
            "recommended_agents": ["frontend"], "optional_agents": ["backend"], "excluded_agents": ["devops"],
            "recommended_skills": [],
            "agent_strategy": "Supabase 스키마·RLS 설계 → Next.js 프론트 → Edge Functions",
            "task_distribution_guide": "frontend agent가 주도. RLS 설계만 backend agent 자문.",
            "is_active": True, "priority": 7, "created_at": now, "updated_at": now,
        },
        # Internal Tool
        {
            "id": uuid.uuid4(), "slug": "internal-tool-react-admin-standard",
            "title": "내부 도구 표준형 (React Admin + FastAPI)",
            "description": "CRUD 중심 관리 도구에 최적화된 React Admin + FastAPI 구성.",
            "tags": ["internal-tool", "admin", "crud"], "primary_tag": "internal-tool",
            "design_pattern": "admin-dashboard", "architecture_pattern": "어드민 대시보드",
            "tech_stack_tags": ["React Admin", "FastAPI", "PostgreSQL", "Docker"],
            "pros": ["CRUD UI 자동 생성", "권한 관리 내장", "빠른 MVP 출시"],
            "cons": ["커스텀 UI 자유도 제한", "React Admin 의존성 큼"],
            "ui_structure": {"frontend": "react-admin", "backend": "fastapi", "database": "postgresql", "auth": "ldap", "deployment": "docker"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "CRUD 우선: React Admin 기본 컴포넌트로 빠른 어드민 구축, 백엔드 API 안정성 집중",
            "implementation_constraints": ["React Admin 컨벤션 준수", "FastAPI REST API 명세를 React Admin 기대 포맷에 맞춤", "권한별 리소스 접근 제어"],
            "recommended_agents": ["backend", "frontend"], "optional_agents": ["devops"], "excluded_agents": ["uiux"],
            "recommended_skills": ["tdd"],
            "agent_strategy": "FastAPI CRUD 엔드포인트 → React Admin 리소스 매핑 → 권한 설정",
            "task_distribution_guide": "backend agent: FastAPI API. frontend agent: React Admin 리소스·커스텀 컴포넌트.",
            "is_active": True, "priority": 10, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "internal-tool-retool-lowcode",
            "title": "내부 도구 로우코드형 (Retool + PostgreSQL)",
            "description": "개발 없이 드래그&드롭으로 내부 도구를 구성하는 로우코드 접근.",
            "tags": ["internal-tool", "lowcode", "no-code"], "primary_tag": "internal-tool",
            "design_pattern": "lowcode-tool", "architecture_pattern": "로우코드 플랫폼",
            "tech_stack_tags": ["Retool", "PostgreSQL", "REST API 연동"],
            "pros": ["개발 시간 90% 단축", "비개발자도 유지보수 가능", "다양한 DB·API 커넥터"],
            "cons": ["Retool 라이선스 비용", "복잡한 로직 구현 한계", "벤더 의존"],
            "ui_structure": {"frontend": "retool", "backend": "retool-queries", "database": "postgresql", "auth": "retool-auth", "deployment": "retool-cloud"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "로우코드 접근: 커스텀 코드 최소화, drag&drop 컴포넌트 조합 우선",
            "implementation_constraints": ["직접 컴포넌트 코딩 지양 - Retool 내장 컴포넌트 활용", "비즈니스 로직은 API 레이어에만 집중", "Retool 쿼리 기반 데이터 연동"],
            "recommended_agents": ["backend", "devops"], "optional_agents": ["uiux"], "excluded_agents": ["frontend"],
            "recommended_skills": ["tdd"],
            "agent_strategy": "백엔드 API 우선 구현 → Retool에서 UI 조립 (프론트엔드 직접 개발 없음)",
            "task_distribution_guide": "backend agent: 데이터 소스 API. devops agent: 배포. UI는 Retool 플랫폼에서 비개발자가 직접 구성.",
            "is_active": True, "priority": 8, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "internal-tool-nextjs-supabase-custom",
            "title": "내부 도구 자체개발형 (Next.js + Supabase)",
            "description": "완전한 커스텀 UI가 필요한 내부 도구를 자체 개발하는 구성.",
            "tags": ["internal-tool", "custom", "fullstack"], "primary_tag": "internal-tool",
            "design_pattern": "custom-internal", "architecture_pattern": "BaaS 기반 커스텀",
            "tech_stack_tags": ["Next.js", "Supabase", "shadcn/ui", "Vercel"],
            "pros": ["완전한 UI 자유도", "shadcn/ui 고품질 컴포넌트", "실시간 기능 즉시 사용"],
            "cons": ["초기 개발 공수↑", "보안 설계 직접 책임"],
            "ui_structure": {"frontend": "next.js", "backend": "supabase", "database": "supabase-postgres", "auth": "supabase-auth", "deployment": "vercel"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "완전 커스텀: UI/UX 자유도 최대화, Supabase로 인프라 부담 최소화",
            "implementation_constraints": ["shadcn/ui 디자인 시스템 일관 사용", "Supabase RLS로 데이터 접근 제어", "Next.js 서버 컴포넌트 적극 활용"],
            "recommended_agents": ["frontend", "uiux"], "optional_agents": ["backend"], "excluded_agents": [],
            "recommended_skills": ["tdd"],
            "agent_strategy": "디자인 시스템 → Next.js 페이지 구조 → Supabase 연동",
            "task_distribution_guide": "frontend agent: Next.js·shadcn. uiux agent: 디자인 시스템·접근성.",
            "is_active": True, "priority": 5, "created_at": now, "updated_at": now,
        },
        # MVP
        {
            "id": uuid.uuid4(), "slug": "mvp-nextjs-vercel-fast",
            "title": "MVP 빠른 배포형 (Next.js + Vercel)",
            "description": "Next.js 단일 프레임워크로 최단 시간 출시에 최적화된 MVP.",
            "tags": ["mvp", "fullstack", "serverless"], "primary_tag": "mvp",
            "design_pattern": "mvp-monolith", "architecture_pattern": "풀스택 모놀리식",
            "tech_stack_tags": ["Next.js", "Prisma", "SQLite→PostgreSQL", "Vercel"],
            "pros": ["push 즉시 Vercel 배포", "프론트/백 코드 통합", "무료 티어로 시작 가능"],
            "cons": ["트래픽 증가 시 리팩토링 필요", "API Routes 성능 한계"],
            "ui_structure": {"frontend": "next.js", "backend": "next.js-api-routes", "database": "sqlite", "auth": "next-auth", "deployment": "vercel"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "빠른 검증: 기술 부채 일부 허용, 출시 속도 최우선. 이후 리팩토링 계획 수립",
            "implementation_constraints": ["완벽한 구조보다 동작하는 코드 우선", "API Routes 한 파일에 로직 집중 허용", "Vercel 무료 티어 제약 내 설계"],
            "recommended_agents": ["backend", "frontend"], "optional_agents": [], "excluded_agents": ["devops"],
            "recommended_skills": [],
            "agent_strategy": "Next.js API Routes로 백엔드·프론트 통합 구현, Vercel 즉시 배포",
            "task_distribution_guide": "fullstack 방식으로 backend+frontend agent 협력. 빠른 반복 우선.",
            "is_active": True, "priority": 10, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "mvp-flask-htmx-ssr",
            "title": "MVP 서버 렌더링형 (Flask + HTMX)",
            "description": "SPA 없이 서버 렌더링으로 구현하는 초경량 MVP.",
            "tags": ["mvp", "python", "minimal"], "primary_tag": "mvp",
            "design_pattern": "mvp-server-rendered", "architecture_pattern": "서버 사이드 렌더링",
            "tech_stack_tags": ["Flask", "HTMX", "SQLite", "Railway"],
            "pros": ["JS 최소화, 빠른 로딩", "단일 Python 코드베이스", "Railway 무료 배포"],
            "cons": ["복잡한 인터랙션 구현 제약", "SPA 수준 UX 불가"],
            "ui_structure": {"frontend": "htmx", "backend": "flask", "database": "sqlite", "auth": "session", "deployment": "railway"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "초경량 서버 렌더링: JS 최소화, Python 단일 코드베이스로 빠른 개발",
            "implementation_constraints": ["HTMX 속성 기반 UI 업데이트", "Jinja2 템플릿 서버 렌더링", "SQLite로 시작, 필요 시 PostgreSQL 이전"],
            "recommended_agents": ["backend"], "optional_agents": [], "excluded_agents": ["frontend", "uiux", "devops"],
            "recommended_skills": [],
            "agent_strategy": "Flask 라우트·템플릿 → HTMX 인터랙션 → Railway 배포",
            "task_distribution_guide": "backend agent 단독으로 Flask·HTMX 통합 구현.",
            "is_active": True, "priority": 5, "created_at": now, "updated_at": now,
        },
        {
            "id": uuid.uuid4(), "slug": "mvp-react-firebase-nocode",
            "title": "MVP 노코드형 (Firebase + React)",
            "description": "Firebase BaaS로 백엔드를 대체하고 React로 빠르게 UI 구성.",
            "tags": ["mvp", "serverless", "baas", "firebase"], "primary_tag": "mvp",
            "design_pattern": "mvp-firebase", "architecture_pattern": "BaaS 서버리스",
            "tech_stack_tags": ["React", "Firebase", "Firestore", "Firebase Hosting"],
            "pros": ["Auth·DB·Hosting 원스톱", "실시간 DB 즉시 사용", "무료 시작 가능"],
            "cons": ["Firebase 벤더 락인", "복잡한 쿼리 제약", "비용 예측 어려움"],
            "ui_structure": {"frontend": "react", "backend": "firebase", "database": "firestore", "auth": "firebase-auth", "deployment": "firebase-hosting"},
            "menu_structure": {}, "color_palette": {},
            "design_philosophy": "Firebase 위임: 백엔드 구현 제로, UI 로직에만 집중",
            "implementation_constraints": ["Firebase Security Rules 필수 설정", "Firestore 쿼리 제약 내 데이터 모델 설계", "Client SDK 직접 사용"],
            "recommended_agents": ["frontend"], "optional_agents": [], "excluded_agents": ["backend", "devops"],
            "recommended_skills": [],
            "agent_strategy": "Firebase 초기화 → Firestore 데이터 모델 → React UI → Security Rules",
            "task_distribution_guide": "frontend agent 단독. Firebase Security Rules 설계 우선.",
            "is_active": True, "priority": 3, "created_at": now, "updated_at": now,
        },
    ])

    # ── seed: app_settings ─────────────────────────────────────────────────────
    op.bulk_insert(
        sa.table(
            "app_settings",
            sa.column("key", sa.String),
            sa.column("value", sa.JSON()),
            sa.column("description", sa.Text),
        ),
        [
            {
                "key": "prototype_variant_count",
                "value": {"value": 3, "min": 2, "max": 5},
                "description": "프로토타입 제안 개수 (2-5, 기본 3)",
            },
            {
                "key": "prototype_rag_top_k",
                "value": {"value": 8, "min": 1, "max": 20},
                "description": "Claude 참조용 카탈로그 top-k (1-20, 기본 8)",
            },
        ],
    )


def downgrade() -> None:
    op.drop_table("app_settings")
    op.drop_index(
        op.f("ix_prototype_catalog_entries_primary_tag"),
        table_name="prototype_catalog_entries",
    )
    op.drop_index(
        op.f("ix_prototype_catalog_entries_slug"),
        table_name="prototype_catalog_entries",
    )
    op.drop_table("prototype_catalog_entries")
    op.drop_index(op.f("ix_prototype_tags_slug"), table_name="prototype_tags")
    op.drop_table("prototype_tags")
