"""시트 잔량 스냅샷 테이블 추가

Revision ID: 9bcfac7d1979
Revises: 2238c05ab5ac
Create Date: 2026-08-05 20:07:42.637542
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision: str = "9bcfac7d1979"
down_revision: str | None = "2238c05ab5ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seat_quota_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("account_email", sa.String(length=255), nullable=False),
        sa.Column("organization_uuid", sa.String(length=64), nullable=True),
        sa.Column("seat_id", sa.Uuid(), nullable=True),
        sa.Column(
            "window",
            sa.Enum("five_hour", "seven_day", "scoped", name="seat_quota_window"),
            nullable=False,
        ),
        sa.Column("scope_name", sa.String(length=128), nullable=True),
        sa.Column("pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("resets_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("ahead_of_pace", sa.Boolean(), nullable=True),
        sa.Column("projected_exhaustion_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("will_last_to_reset", sa.Boolean(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["seat_id"], ["user_anthropic_credentials.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seat_quota_snapshots_account_email"),
        "seat_quota_snapshots",
        ["account_email"],
        unique=False,
    )
    op.create_index(
        "ix_seat_quota_snapshots_account_window_scope",
        "seat_quota_snapshots",
        ["account_email", "window", "scope_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seat_quota_snapshots_captured_at"),
        "seat_quota_snapshots",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seat_quota_snapshots_seat_id"), "seat_quota_snapshots", ["seat_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_seat_quota_snapshots_seat_id"), table_name="seat_quota_snapshots")
    op.drop_index(op.f("ix_seat_quota_snapshots_captured_at"), table_name="seat_quota_snapshots")
    op.drop_index("ix_seat_quota_snapshots_account_window_scope", table_name="seat_quota_snapshots")
    op.drop_index(op.f("ix_seat_quota_snapshots_account_email"), table_name="seat_quota_snapshots")
    op.drop_table("seat_quota_snapshots")
    # ### end Alembic commands ###
