"""스키마_전체_동기화

Revision ID: c255febcea16
Revises: 011
Create Date: 2026-04-16 14:53:00.611427
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision: str = "c255febcea16"
down_revision: str | None = "011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_ai", sa.String(length=100), nullable=True),
        sa.Column("reviewed_by_ai", sa.String(length=100), nullable=True),
        sa.Column("revision_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artifacts_project_id"), "artifacts", ["project_id"], unique=False)
    op.create_table(
        "orchestrator_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("prompt_template", sa.Text(), nullable=True),
        sa.Column("risk_flags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orchestrator_sessions_project_id"),
        "orchestrator_sessions",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "artifact_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("old_status", sa.String(length=20), nullable=True),
        sa.Column("new_status", sa.String(length=20), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifact_events_artifact_id"), "artifact_events", ["artifact_id"], unique=False
    )
    op.create_table(
        "phase_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("old_phase", sa.String(length=20), nullable=True),
        sa.Column("new_phase", sa.String(length=20), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["orchestrator_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phase_events_session_id"), "phase_events", ["session_id"], unique=False
    )
    op.create_table(
        "quality_gate_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("checks_total", sa.Integer(), nullable=False),
        sa.Column("checks_passed", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=True),
        sa.Column("verdict_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["orchestrator_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_gate_runs_session_id"), "quality_gate_runs", ["session_id"], unique=False
    )
    op.create_table(
        "subtasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assigned_role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("depends_on", sa.JSON(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["orchestrator_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subtasks_session_id"), "subtasks", ["session_id"], unique=False)
    op.create_table(
        "quality_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("passed", sa.String(length=5), nullable=False),
        sa.Column("agent_id", sa.String(length=100), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("findings", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["quality_gate_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quality_checks_run_id"), "quality_checks", ["run_id"], unique=False)
    op.create_table(
        "quality_gate_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["quality_gate_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_gate_events_run_id"), "quality_gate_events", ["run_id"], unique=False
    )
    op.create_table(
        "review_rounds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("subtask_id", sa.Uuid(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("main_ai_role", sa.String(length=50), nullable=False),
        sa.Column("draft_content", sa.Text(), nullable=False),
        sa.Column("sub_ai_role", sa.String(length=50), nullable=True),
        sa.Column("review_type", sa.String(length=30), nullable=True),
        sa.Column("review_content", sa.Text(), nullable=True),
        sa.Column("review_score", sa.Integer(), nullable=True),
        sa.Column("diff_summary", sa.Text(), nullable=True),
        sa.Column("merged_content", sa.Text(), nullable=True),
        sa.Column("merge_strategy", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["orchestrator_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subtask_id"], ["subtasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_rounds_session_id"), "review_rounds", ["session_id"], unique=False
    )
    op.create_table(
        "review_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("round_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["round_id"], ["review_rounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_events_round_id"), "review_events", ["round_id"], unique=False)
    op.alter_column(
        "agent_connections",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "agent_connections",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agent_connections",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("agent_connections_agent_token_key"), "agent_connections", type_="unique"
    )
    op.drop_index(op.f("ix_agent_connections_agent_token"), table_name="agent_connections")
    op.create_index(
        op.f("ix_agent_connections_agent_token"), "agent_connections", ["agent_token"], unique=True
    )
    op.alter_column(
        "agents",
        "config_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "agents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("agents_slug_key"), "agents", type_="unique")
    op.drop_index(op.f("ix_agents_slug"), table_name="agents")
    op.create_index(op.f("ix_agents_slug"), "agents", ["slug"], unique=True)
    op.drop_constraint(op.f("central_contracts_slug_key"), "central_contracts", type_="unique")
    op.drop_index(op.f("ix_central_contracts_contract_type"), table_name="central_contracts")
    op.drop_index(op.f("ix_central_contracts_slug"), table_name="central_contracts")
    op.create_index(op.f("ix_central_contracts_slug"), "central_contracts", ["slug"], unique=True)
    op.alter_column(
        "licenses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "licenses",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("licenses_license_key_key"), "licenses", type_="unique")
    op.drop_index(op.f("ix_licenses_license_key"), table_name="licenses")
    op.create_index(op.f("ix_licenses_license_key"), "licenses", ["license_key"], unique=True)
    op.alter_column(
        "mcp_servers",
        "config_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "mcp_servers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "mcp_servers",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("mcp_servers_slug_key"), "mcp_servers", type_="unique")
    op.drop_index(op.f("ix_mcp_servers_slug"), table_name="mcp_servers")
    op.create_index(op.f("ix_mcp_servers_slug"), "mcp_servers", ["slug"], unique=True)
    op.alter_column(
        "organization_memberships",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "organization_memberships",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "organizations",
        "tech_stack",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "organizations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "organizations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("uq_pm_metrics_pm_id"), "pm_metrics", type_="unique")
    op.drop_index(op.f("ix_pm_metrics_pm_id"), table_name="pm_metrics")
    op.create_index(op.f("ix_pm_metrics_pm_id"), "pm_metrics", ["pm_id"], unique=True)
    op.drop_constraint(op.f("pm_profiles_slug_key"), "pm_profiles", type_="unique")
    op.drop_index(op.f("ix_pm_profiles_slug"), table_name="pm_profiles")
    op.create_index(op.f("ix_pm_profiles_slug"), "pm_profiles", ["slug"], unique=True)
    op.drop_index(op.f("ix_presets_maturity_level"), table_name="presets")
    op.drop_constraint(op.f("presets_slug_key"), "presets", type_="unique")
    op.drop_index(op.f("ix_presets_slug"), table_name="presets")
    op.create_index(op.f("ix_presets_slug"), "presets", ["slug"], unique=True)
    op.alter_column(
        "project_configs",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "project_configs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_configs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "projects",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "projects",
        "wizard_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.add_column("prototype_sessions", sa.Column("solution_prompt", sa.Text(), nullable=True))
    op.add_column("prototype_sessions", sa.Column("parsed_requirements", sa.JSON(), nullable=True))
    op.add_column(
        "prototype_sessions", sa.Column("selected_prototype_id", sa.Uuid(), nullable=True)
    )
    op.add_column("prototype_sessions", sa.Column("selected_pm_id", sa.Uuid(), nullable=True))
    op.add_column(
        "prototype_sessions",
        sa.Column("current_step", sa.Integer(), nullable=False, server_default="1"),
    )
    op.add_column("prototype_sessions", sa.Column("metadata", sa.JSON(), nullable=True))
    op.add_column(
        "prototype_sessions", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "prototype_sessions",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=30),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.create_foreign_key(
        None,
        "prototype_sessions",
        "prototypes",
        ["selected_prototype_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        None, "prototype_sessions", "pm_profiles", ["selected_pm_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("prototype_sessions", "user_input")
    op.add_column(
        "prototypes", sa.Column("variant_index", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "prototypes", sa.Column("title", sa.String(length=200), nullable=False, server_default="")
    )
    op.add_column("prototypes", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("prototypes", sa.Column("design_pattern", sa.String(length=100), nullable=True))
    op.add_column("prototypes", sa.Column("menu_structure", sa.JSON(), nullable=True))
    op.add_column("prototypes", sa.Column("ui_structure", sa.JSON(), nullable=True))
    op.add_column("prototypes", sa.Column("color_palette", sa.JSON(), nullable=True))
    op.add_column("prototypes", sa.Column("thumbnail_url", sa.String(length=500), nullable=True))
    op.add_column("prototypes", sa.Column("figma_file_key", sa.String(length=200), nullable=True))
    op.add_column("prototypes", sa.Column("figma_embed_url", sa.String(length=500), nullable=True))
    op.add_column(
        "prototypes",
        sa.Column("status", sa.String(length=30), nullable=False, server_default="draft"),
    )
    op.add_column("prototypes", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_column("prototypes", "name")
    op.drop_column("prototypes", "is_selected")
    op.drop_column("prototypes", "solution_type")
    op.drop_column("prototypes", "reasoning")
    op.drop_column("prototypes", "config")
    op.alter_column(
        "role_audit_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "skills",
        "config_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "skills",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "skills",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("skills_slug_key"), "skills", type_="unique")
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=True)
    op.alter_column(
        "ticket_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tickets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tickets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "tickets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tickets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ticket_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("skills_slug_key"), "skills", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "skills",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "skills",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "skills",
        "config_schema",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "role_audit_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "prototypes",
        sa.Column(
            "config", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "prototypes", sa.Column("reasoning", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "prototypes",
        sa.Column("solution_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.add_column(
        "prototypes",
        sa.Column(
            "is_selected",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "prototypes", sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False)
    )
    op.drop_column("prototypes", "updated_at")
    op.drop_column("prototypes", "status")
    op.drop_column("prototypes", "figma_embed_url")
    op.drop_column("prototypes", "figma_file_key")
    op.drop_column("prototypes", "thumbnail_url")
    op.drop_column("prototypes", "color_palette")
    op.drop_column("prototypes", "ui_structure")
    op.drop_column("prototypes", "menu_structure")
    op.drop_column("prototypes", "design_pattern")
    op.drop_column("prototypes", "description")
    op.drop_column("prototypes", "title")
    op.drop_column("prototypes", "variant_index")
    op.add_column(
        "prototype_sessions",
        sa.Column(
            "user_input",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "prototype_sessions", type_="foreignkey")
    op.drop_constraint(None, "prototype_sessions", type_="foreignkey")
    op.alter_column(
        "prototype_sessions",
        "status",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.drop_column("prototype_sessions", "updated_at")
    op.drop_column("prototype_sessions", "metadata")
    op.drop_column("prototype_sessions", "current_step")
    op.drop_column("prototype_sessions", "selected_pm_id")
    op.drop_column("prototype_sessions", "selected_prototype_id")
    op.drop_column("prototype_sessions", "parsed_requirements")
    op.drop_column("prototype_sessions", "solution_prompt")
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "projects",
        "wizard_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "settings",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "project_configs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_configs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "project_configs",
        "config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_presets_slug"), table_name="presets")
    op.create_index(op.f("ix_presets_slug"), "presets", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("presets_slug_key"), "presets", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("ix_presets_maturity_level"), "presets", ["maturity_level"], unique=False)
    op.drop_index(op.f("ix_pm_profiles_slug"), table_name="pm_profiles")
    op.create_index(op.f("ix_pm_profiles_slug"), "pm_profiles", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("pm_profiles_slug_key"), "pm_profiles", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_pm_metrics_pm_id"), table_name="pm_metrics")
    op.create_index(op.f("ix_pm_metrics_pm_id"), "pm_metrics", ["pm_id"], unique=False)
    op.create_unique_constraint(
        op.f("uq_pm_metrics_pm_id"), "pm_metrics", ["pm_id"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "organizations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "organizations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "organizations",
        "tech_stack",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "organization_memberships",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "organization_memberships",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_mcp_servers_slug"), table_name="mcp_servers")
    op.create_index(op.f("ix_mcp_servers_slug"), "mcp_servers", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("mcp_servers_slug_key"), "mcp_servers", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "mcp_servers",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "mcp_servers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "mcp_servers",
        "config_schema",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_licenses_license_key"), table_name="licenses")
    op.create_index(op.f("ix_licenses_license_key"), "licenses", ["license_key"], unique=False)
    op.create_unique_constraint(
        op.f("licenses_license_key_key"),
        "licenses",
        ["license_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "licenses",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "licenses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_central_contracts_slug"), table_name="central_contracts")
    op.create_index(op.f("ix_central_contracts_slug"), "central_contracts", ["slug"], unique=False)
    op.create_index(
        op.f("ix_central_contracts_contract_type"),
        "central_contracts",
        ["contract_type"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("central_contracts_slug_key"),
        "central_contracts",
        ["slug"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_agents_slug"), table_name="agents")
    op.create_index(op.f("ix_agents_slug"), "agents", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("agents_slug_key"), "agents", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "agents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agents",
        "config_schema",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_agent_connections_agent_token"), table_name="agent_connections")
    op.create_index(
        op.f("ix_agent_connections_agent_token"), "agent_connections", ["agent_token"], unique=False
    )
    op.create_unique_constraint(
        op.f("agent_connections_agent_token_key"),
        "agent_connections",
        ["agent_token"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "agent_connections",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agent_connections",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agent_connections",
        "metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_review_events_round_id"), table_name="review_events")
    op.drop_table("review_events")
    op.drop_index(op.f("ix_review_rounds_session_id"), table_name="review_rounds")
    op.drop_table("review_rounds")
    op.drop_index(op.f("ix_quality_gate_events_run_id"), table_name="quality_gate_events")
    op.drop_table("quality_gate_events")
    op.drop_index(op.f("ix_quality_checks_run_id"), table_name="quality_checks")
    op.drop_table("quality_checks")
    op.drop_index(op.f("ix_subtasks_session_id"), table_name="subtasks")
    op.drop_table("subtasks")
    op.drop_index(op.f("ix_quality_gate_runs_session_id"), table_name="quality_gate_runs")
    op.drop_table("quality_gate_runs")
    op.drop_index(op.f("ix_phase_events_session_id"), table_name="phase_events")
    op.drop_table("phase_events")
    op.drop_index(op.f("ix_artifact_events_artifact_id"), table_name="artifact_events")
    op.drop_table("artifact_events")
    op.drop_index(op.f("ix_orchestrator_sessions_project_id"), table_name="orchestrator_sessions")
    op.drop_table("orchestrator_sessions")
    op.drop_index(op.f("ix_artifacts_project_id"), table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
