"""프로젝트별 Linear webhook 시크릿·webhook ID 컬럼 추가

Revision ID: caba8cf24f84
Revises: 9bcfac7d1979
Create Date: 2026-08-07 16:35:33.750894
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision: str = "caba8cf24f84"
down_revision: str | None = "9bcfac7d1979"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_linear_credentials",
        sa.Column("webhook_secret", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "project_linear_credentials",
        sa.Column("linear_webhook_id", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_linear_credentials", "linear_webhook_id")
    op.drop_column("project_linear_credentials", "webhook_secret")
    # ### end Alembic commands ###
